In [0]:
#importing the libraries
import numpy as np
import pandas as pd

In [0]:
#import dataset
data =pd.read_csv("/content/churndata.csv",sep=";")

In [6]:
data.head()

RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]

In [0]:
#create matrix for target variable and matrix of feature
X = data.iloc[:,3:13].values
y = data.iloc[:,13].values

In [10]:
#ukuran X awal itu 10
X

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [9]:
X.shape

(10000, 10)

In [11]:
y

array([1, 0, 1, ..., 1, 1, 0])

In [0]:
#label variable categoric. we have two categoric feature in character. 
#So we have to change to number label. Country have 3 categories are France,Germany, and spain, Its change to 0,1,2
#gender change to 0,1
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_X_1 =LabelEncoder()


In [0]:
X[:, 1] = labelencoder_X_1.fit_transform(X[:, 1])
labelencoder_X_2 = LabelEncoder()
X[:, 2] = labelencoder_X_2.fit_transform(X[:, 2])

In [14]:
X

array([[619, 0, 0, ..., 1, 1, 101348.88],
       [608, 2, 0, ..., 0, 1, 112542.58],
       [502, 0, 0, ..., 1, 0, 113931.57],
       ...,
       [709, 0, 0, ..., 0, 1, 42085.58],
       [772, 1, 1, ..., 1, 0, 92888.52],
       [792, 0, 0, ..., 1, 0, 38190.78]], dtype=object)

In [15]:
X.shape

(10000, 10)

In [0]:
#one = OneHotEncoder(categorical_features=[1])
#X = one.fit_transform(X).toarray()

In [0]:
#Create dummy variable in python. 
#LabelEncoder has replaced France with 0, Germany 1 and Spain 2 but Germany is not 
#higher than France and France is not smaller than Spain so we need to create a dummy variable for Country.
from sklearn.compose import ColumnTransformer
ct = ColumnTransformer([("Geography", OneHotEncoder(), [1])], remainder = 'passthrough')
X = ct.fit_transform(X)

In [18]:
X

array([[1.0, 0.0, 0.0, ..., 1, 1, 101348.88],
       [0.0, 0.0, 1.0, ..., 0, 1, 112542.58],
       [1.0, 0.0, 0.0, ..., 1, 0, 113931.57],
       ...,
       [1.0, 0.0, 0.0, ..., 0, 1, 42085.58],
       [0.0, 1.0, 0.0, ..., 1, 0, 92888.52],
       [1.0, 0.0, 0.0, ..., 1, 0, 38190.78]], dtype=object)

In [0]:
len(X)

10000

In [19]:
X.shape

(10000, 12)

In [20]:
X[1,:]

array([0.0, 0.0, 1.0, 608, 0, 41, 1, 83807.86, 1, 0, 1, 112542.58],
      dtype=object)

In [0]:
#split train and test
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3)

In [0]:
#feature scalling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [0]:
# Importing the Keras libraries and packages
import os
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.layers import Dense, Flatten
from tensorflow.keras.models import Sequential

In [0]:
#Initializing Neural Network
classifier = Sequential()

In [0]:
# Adding the input layer and the first hidden layer
classifier.add(Dense(200,input_dim = 12, activation = 'relu' ))

In [0]:
# Adding the second hidden layer
classifier.add(Dense(200,  activation = 'relu'))

In [0]:
#output layer
# Adding the output layer
classifier.add(Dense(1,  activation = 'sigmoid'))

In [0]:
# Compiling Neural Network
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [58]:
# Fitting our model 
classifier.fit(X_train, y_train, batch_size = 100, epoch = 100,validation_data=(X_test,y_test))

70/70 [==============================] - 0s 4ms/step - loss: 0.3307 - accuracy: 0.8640 - val_loss: 0.3338 - val_accuracy: 0.8670


In [0]:
# Predicting the Test set results
#if y_pred is larger than 0.5 it returns true(1) else false(2)
y_pred = classifier.predict(X_test)
y_pred_1 = (y_pred > 0.5)

In [71]:
y_pred

array([[0.05023879],
       [0.01500511],
       [0.06888208],
       ...,
       [0.06213629],
       [0.26854149],
       [0.01974717]], dtype=float32)

In [66]:
y_pred_1

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

In [0]:
# Creating the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred_1)

In [72]:
print(cm) #0 1

[[2298   85]
 [ 314  303]]


In [70]:
y_test

array([0, 0, 1, ..., 0, 0, 0])